# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: build
on: [ push, pull_request ]

jobs:
  test:
    name: Test On Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: https://code.forgejo.org/actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: https://code.forgejo.org/actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install module
        run: python -m pip install .

      - name: Run Unit Tests
        run: python -m unittest -v

  test-action:
    name: Test Action
    runs-on: ubuntu-24.04
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v5

      - name: Get Changelog Information
        uses: ./
        id: yaclog-show
        with:
          changelog-path: 'tests/Test-Changelog.md'

      - name: Get Changelog Information (Unreleased)
        uses: ./
        id: yaclog-show-unreleased
        with:
          changelog-path: 'tests/Test-Changelog-Unreleased.md'

      - name: Copy Body File
        run:
          cp ${{ steps.yaclog-show.outputs.body-file }} body.md

      - name: Fail
        if: >
          !(
          steps.yaclog-show.outputs.name == '0.13.0 "Aquarius"' &&
          steps.yaclog-show.outputs.header == '## 0.13.0 "Aquarius" - 1970-04-11 [YANKED]' &&
          steps.yaclog-show.outputs.version == '0.13.0' &&
          steps.yaclog-show-unreleased.outputs.version == '0.13.1' &&
          endsWith(steps.yaclog-show.outputs.changelog, 'tests/Test-Changelog.md') &&
          hashFiles('body.md') == 'ad49b5c946b7d361db1c3dacc73de4f6222cca6272aab426786de168eede702b'
          )
        run: |
          echo "Action self-test failed!"
          echo "yaclog-show:\n ${{ toJSON(steps.yaclog-show.outputs) }}"
          echo "yaclog-show-unreleased:\n${{ toJSON(steps.yaclog-show.outputs) }}"
          echo "${{ hashFiles('body.md') }}"
          false

  build:
    name: Build Distribution
    needs:
      - test
      - test-action
    runs-on: ubuntu-22.04
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v5

      - name: Set up Python
        uses: https://code.forgejo.org/actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - uses: https://code.forgejo.org/actions/upload-artifact@v4
        with:
          name: python-distribution
          path: dist/
          compression-level: 0 # already compressed

  publish:
    name: Publish Package
    if: forge.event_name == 'push' && startsWith(forge.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v5

      - uses: https://code.forgejo.org/actions/download-artifact@v4
        with:
          name: python-distribution
          path: dist/

      - name: Get Changelog Information
        id: yaclog-show
        uses: ./ # self-hosting!

      - name: Publish to PyPI
        uses: github.com/pypa/gh-action-pypi-publish@release/v1